import { Student, Guardian } from "./types";

export const studentData: Student[] = [
  {
    id: 1,
    name: "John Doe",
    user_id: "USR001",
    phone_number: "+1234567890",
    reg_date: "2025-01-20",
    email: "johndoe@example.com",
    class: "Mathematics",
  },
  {
    id: 2,
    name: "Jane Smith",
    user_id: "USR002",
    phone_number: "+1234567891",
    reg_date: "2025-01-21",
    email: "janesmith@example.com",
    class: "Science",
  },
  {
    id: 3,
    name: "Alice Johnson",
    user_id: "USR003",
    phone_number: "+1234567892",
    reg_date: "2025-01-22",
    email: "alicejohnson@example.com",
    class: "English",
  },
  {
    id: 4,
    name: "Robert Brown",
    user_id: "USR004",
    phone_number: "+1234567893",
    reg_date: "2025-01-23",
    email: "robertbrown@example.com",
    class: "History",
  },
  {
    id: 5,
    name: "Emily Davis",
    user_id: "USR005",
    phone_number: "+1234567894",
    reg_date: "2025-01-24",
    email: "emilydavis@example.com",
    class: "Geography",
  },
  {
    id: 6,
    name: "Michael Wilson",
    user_id: "USR006",
    phone_number: "+1234567895",
    reg_date: "2025-01-25",
    email: "michaelwilson@example.com",
    class: "Physics",
  },
  {
    id: 7,
    name: "Sophia Taylor",
    user_id: "USR007",
    phone_number: "+1234567896",
    reg_date: "2025-01-26",
    email: "sophiataylor@example.com",
    class: "Chemistry",
  },
  {
    id: 8,
    name: "David Martinez",
    user_id: "USR008",
    phone_number: "+1234567897",
    reg_date: "2025-01-27",
    email: "davidmartinez@example.com",
    class: "Biology",
  },
  {
    id: 9,
    name: "Olivia Anderson",
    user_id: "USR009",
    phone_number: "+1234567898",
    reg_date: "2025-01-28",
    email: "oliviaanderson@example.com",
    class: "Literature",
  },
  {
    id: 10,
    name: "James Thomas",
    user_id: "USR010",
    phone_number: "+1234567899",
    reg_date: "2025-01-29",
    email: "jamesthomas@example.com",
    class: "Computer Science",
  },
];

export const guardianData: Guardian[] = [
  {
    id: 2,
    name: "Jane Doe",
    user_id: "USR002",
    phone_number: "+9876543210",
    reg_date: "2025-01-22",
    email: "janedoe@example.com",
  },
  {
    id: 3,
    name: "Michael Smith",
    user_id: "USR003",
    phone_number: "+1122334455",
    reg_date: "2025-02-10",
    email: "michaelsmith@example.com",
  },
  {
    id: 4,
    name: "Sarah Johnson",
    user_id: "USR004",
    phone_number: "+9988776655",
    reg_date: "2025-02-15",
    email: "sarahjohnson@example.com",
  },
  {
    id: 5,
    name: "David Williams",
    user_id: "USR005",
    phone_number: "+6677889900",
    reg_date: "2025-03-01",
    email: "davidwilliams@example.com",
  },
  {
    id: 6,
    name: "Emily Brown",
    user_id: "USR006",
    phone_number: "+5544332211",
    reg_date: "2025-03-12",
    email: "emilybrown@example.com",
  },
  {
    id: 7,
    name: "Robert Jones",
    user_id: "USR007",
    phone_number: "+4455667788",
    reg_date: "2025-04-05",
    email: "robertjones@example.com",
  },
  {
    id: 8,
    name: "Olivia Martinez",
    user_id: "USR008",
    phone_number: "+3322114455",
    reg_date: "2025-04-18",
    email: "oliviamartinez@example.com",
  },

  {
    id: 9,
    name: "William Davis",
    user_id: "USR009",
    phone_number: "+1199887766",
    reg_date: "2025-05-07",
    email: "williamdavis@example.com",
  },

  {
    id: 10,
    name: "Sophia Wilson",
    user_id: "USR010",
    phone_number: "+6677554433",
    reg_date: "2025-05-20",
    email: "sophiawilson@example.com",
  },
  {
    id: 11,
    name: "James Anderson",
    user_id: "USR011",
    phone_number: "+1122446688",
    reg_date: "2025-06-03",
    email: "jamesanderson@example.com",
  },
  {
    id: 12,
    name: "Charlotte Thomas",
    user_id: "USR012",
    phone_number: "+3344556677",
    reg_date: "2025-06-15",
    email: "charlottethomas@example.com",
  },
];

export const StudentActionsData = [
  { id: 1, label: "View Student Details" },
  { id: 2, label: "Suspend Student" },
  { id: 3, label: "Subscribe for Student" },
  { id: 4, label: "Subscription History" },
  { id: 5, label: "Delete Student" },
];

export const classData = [
  { key: "1", class: "Common Entrance Prep", id: "Exam", no_of_subject: 20 },
  { key: "2", class: "Common Entrance Prep", id: "Exam", no_of_subject: 10 },
  { key: "3", class: "Common Entrance Prep", id: "Exam", no_of_subject: 70 },
  { key: "4", class: "Disabled User", id: 99, no_of_subject: 2 },
];

export const subjectData = [
  {
    id: 1,
    class: "Common Entrance",
    subjects: [
      {
        key: 1,
        subject: "Mathematics",
        subject_code: "MA",
        number_of_topics: 10,
      },
      {
        key: 2,
        subject: "English",
        subject_code: "MA",
        number_of_topics: 20,
      },
    ],
  },
  {
    id: 2,
    class: "Waec",
    subjects: [
      {
        key: 3,
        subject: "Mathematics",
        subject_code: "MA",
        number_of_topics: 10,
      },
      {
        key: 4,
        subject: "English",
        subject_code: "MA",
        number_of_topics: 20,
      },
      {
        key: 5,
        subject: "Basic Science",
        subject_code: "MA",
        number_of_topics: 5,
      },
    ],
  },
];
